version: '3.8'
services:
  laravel.test:
    image: sail-8.3/app
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html:ro'
    depends_on:
      - laravel.test
    networks:
      - sail
    
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  postgres-data:
